/**
 * Setup Runner — Applies configuration by shelling out to mb CLI
 * 
 * This module applies the wizard's SetupPlan by invoking mb config set
 * commands. It delegates all persistence to the Rust CLI to ensure
 * consistency with the existing codebase.
 */

import { spawn } from 'child_process';
import { join } from 'path';
import { homedir } from 'os';
import { existsSync, writeFileSync, chmodSync } from 'fs';
import type { SetupPlan, ProviderId } from './types.js';
import { PROVIDER_ENV_VARS } from './types.js';

export interface SetupResult {
  success: boolean;
  error?: string;
  commands: string[];
}

/** Get the mb binary path */
function getMbPath(): string {
  const isWindows = process.platform === 'win32';
  const exeExt = isWindows ? '.exe' : '';
  
  // Prefer the installed binary in ~/.memory_bank/bin
  const userBinPath = join(homedir(), '.memory_bank', 'bin', `mb${exeExt}`);
  if (existsSync(userBinPath)) {
    return userBinPath;
  }
  
  // Fall back to PATH
  return 'mb';
}

/** Run a single mb config set command */
function runConfigSet(key: string, value: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const mbPath = getMbPath();
    const proc = spawn(mbPath, ['config', 'set', key, value], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    
    let stderr = '';
    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });
    
    proc.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(stderr || `Command failed with code ${code}`));
      }
    });
    
    proc.on('error', (err) => {
      reject(err);
    });
  });
}

/** Write secrets.env file directly */
function writeSecretsEnv(plan: SetupPlan): void {
  const envVarName = PROVIDER_ENV_VARS[plan.provider];
  if (!envVarName || !plan.apiKey) return;
  
  const secretsPath = join(homedir(), '.memory_bank', 'secrets.env');
  
  const content = `# Memory Bank Secrets - Auto-generated by setup wizard\n${envVarName}=${plan.apiKey}\n`;
  
  writeFileSync(secretsPath, content, { mode: 0o600 });
}

/** Apply the complete setup plan */
export async function applySetupPlan(plan: SetupPlan): Promise<SetupResult> {
  const commands: string[] = [];
  const errors: string[] = [];
  
  try {
    // 1. Set namespace
    commands.push(`mb config set active_namespace ${plan.namespace}`);
    await runConfigSet('active_namespace', plan.namespace);
    
    // 2. Set provider
    commands.push(`mb config set server.llm_provider ${plan.provider}`);
    await runConfigSet('server.llm_provider', plan.provider);
    
    // 3. Set model
    commands.push(`mb config set server.llm_model ${plan.model}`);
    await runConfigSet('server.llm_model', plan.model);
    
    // 4. Set port
    commands.push(`mb config set service.port ${plan.port}`);
    await runConfigSet('service.port', String(plan.port));
    
    // 5. Set autostart
    commands.push(`mb config set service.autostart ${plan.autostart}`);
    await runConfigSet('service.autostart', String(plan.autostart));
    
    // 6. Set custom URLs if needed
    if (plan.openaiUrl) {
      commands.push(`mb config set server.openai_url ${plan.openaiUrl}`);
      await runConfigSet('server.openai_url', plan.openaiUrl);
    }
    
    if (plan.ollamaUrl) {
      commands.push(`mb config set server.ollama_url ${plan.ollamaUrl}`);
      await runConfigSet('server.ollama_url', plan.ollamaUrl);
    }
    
    // 7. Write secrets
    if (plan.apiKey) {
      writeSecretsEnv(plan);
      commands.push('Write secrets.env');
    }
    
    // 8. Configure selected agents
    for (const agent of plan.selectedAgents) {
      const configKey = `integrations.${agent.replace('_', '.')}.configured`;
      commands.push(`mb config set ${configKey} true`);
      await runConfigSet(configKey, 'true');
    }
    
    return {
      success: true,
      commands,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
      commands,
    };
  }
}

/** Check if configuration already exists */
export function hasExistingConfig(): boolean {
  const configPath = join(homedir(), '.memory_bank', 'settings.toml');
  return existsSync(configPath);
}

/** Start the Memory Bank service */
export async function startService(): Promise<boolean> {
  return new Promise((resolve) => {
    const mbPath = getMbPath();
    const proc = spawn(mbPath, ['service', 'start'], {
      stdio: 'ignore',
    });
    
    proc.on('close', (code) => {
      resolve(code === 0);
    });
    
    proc.on('error', () => {
      resolve(false);
    });
  });
}
